import { Roboto, Roboto_Mono } from 'next/font/google';
import './globals.css';
import type { Metadata } from 'next';

const roboto = Roboto({
    weight: ['400', '700'],
    subsets: ['latin'],
    variable: '--font-roboto',
    display: 'swap',
});

const robotoMono = Roboto_Mono({
    subsets: ['latin'],
    variable: '--font-roboto-mono',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${roboto.className} ${robotoMono.className} antialiased`}>
                {children}
            </body>
        </html>
    );
}